# remove "--" from filename for run file
# readmore : https://github.com/SamKirkland/FTP-Deploy-Action

name: ğŸª FTP-DEPLOY

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: ğŸª FTP-Deploy
    runs-on: ubuntu-latest
    steps:

      - name: ğŸ” Get latest code
        uses: actions/checkout@v2

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER}}
          password: ${{secrets.FTP_PASSWORD}}
          protocol: ftps
          port: 21
          dangerous-clean-slate: false
          exclude: |
            - *.git
            - *.github
            - *.gitignore
            - *.txt
            - *.ftp*
            - *.vscode
            - */.github/*
            - */.bkps/*
            - */.trash/*
            - */uploads/*
